version: "3"

services:
   vsi-site:
      image: wordpress:latest
      env_file:
         - ./.gitsecret/secrets/vsi-site.env
      ports:
         - 8888:80
   mysql:
      image: mysql:5.7
      env_file:
         - ./.gitsecret/secrets/vsi-site.env
      ports:
         - 33006:3306