version: "3"

services:
   vsi-site:
      image: wordpress:fpm-alpine
      env_file:
         - ./.gitsecret/secrets/vsi-site.env
      environment:
         - MYSQL_HOST=mysql
      ports:
         - 8888:80
   mysql:
      image: mysql:latest
      env_file:
         - ./.gitsecret/secrets/vsi-site.env
      ports:
         - 33006:3306